# Generated by Django 3.1 on 2022-02-19 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_learn', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialization',
            old_name='Specialization',
            new_name='department',
        ),
    ]
